# Generated by Django 6.0.5 on 2026-05-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('reaction', 'Reaction'), ('follow', 'Follow'), ('new_post', 'New Post'), ('recommend', 'Recommendation')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('heart', 'Heart')], default='heart', max_length=10),
        ),
    ]
