# Generated by Django 6.0.5 on 2026-05-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
