# Generated by Django 6.0.5 on 2026-05-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_remove_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
