# Generated by Django 6.0.5 on 2026-05-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_add_is_edited_to_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
